CONFIG_SENSOR=y
CONFIG_W1=y

CONFIG_LOG=y
CONFIG_SENSOR_LOG_LEVEL_DBG=y

# Enable 1-Wire Subsystem
CONFIG_W1=y

# Enable Sensor API and DS18B20 Driver
CONFIG_SENSOR=y
CONFIG_DS18B20=y

CONFIG_SENSOR=y

CONFIG_WIFI=y
CONFIG_WIFI_ESP32=y
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_DHCPV4=y

CONFIG_NET_SOCKETS=y
CONFIG_NET_TCP=y
CONFIG_MQTT_LIB=y

CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_MAIN_STACK_SIZE=8192
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_CBPRINTF_FP_SUPPORT=y
